// src/components/Editor/Toolbar.tsx
import { memo, useEffect, useMemo, useRef, useState } from "react";
import { NewDirectionIcon, StatusDot, JournalIcon } from "../../lib/icons";
import type { PathCollection } from "../../lib/types";
import { isGhostPath } from "../../lib/types";
import { buildPathColorMap, colorForPath, isRoot } from "../../lib/pathAwareness";
import { useT } from "../../lib/i18n";
import { SK } from "../../lib/platform";

interface Props {
  /** v2 path collections (source of truth for the switcher). */
  collections: PathCollection[];
  /** Name of the root collection (usually "main"). */
  rootName: string;
  /** Currently-focused collection name. */
  currentPath: string;
  checkpointCount: number;
  dirty: boolean;
  /** Monotonic nonce bumped whenever a save just completed. */
  lastSavedAt?: number;
  /** When false (basic workspace mode), the path pill + path actions are hidden. */
  mappingEnabled?: boolean;
  onSwitchPath: (name: string) => void;
  /** "+ Branch this note" — pre-seed with current note/path context. */
  onBranchFromHere: () => void;
  /** Open the full paths graph (the fullscreen Forking Road). */
  onOpenPaths: () => void;
  /** Open the side-by-side compare modal. Hidden if there's only one path. */
  onComparePaths?: () => void;
  /** Open the connection graph (Map overlay). */
  onOpenMap: () => void;
  /** Click the condition pill to set/edit it for the current path. */
  onEditCurrentCondition: () => void;
  /** Focus/zen mode is on — show an indicator chip + exit button so the
   *  user always knows they're in it and how to leave. */
  focusMode?: boolean;
  onExitFocus?: () => void;
  /** When the active note is a daily journal (slug starts with "daily/"),
   *  the toolbar surfaces a label showing which day is open plus a
   *  button that opens the month calendar — so users can jump to any
   *  past (or future) day without going back to the sidebar. */
  dailyDate?: string | null;
  /** Open the month calendar anchored below the journal pill. Signature
   *  includes the pill's bounding rect so the consumer can position a
   *  popover instead of rendering a centred modal. */
  onOpenJournalCalendar?: (anchor: DOMRect) => void;
}

/**
 * The top-of-editor chrome. A single line that answers three questions
 * at a glance: *where am I* (path name + colored dot + condition),
 * *what can I do right now* (branch this / open paths), and *is my work
 * saved* (checkpoint count + save indicator).
 *
 * Ambient, not loud — the user shouldn't have to "read" this to know
 * they're on `if-seattle`, just glance.
 */
function ToolbarInner({
  collections,
  rootName,
  currentPath,
  checkpointCount,
  dirty,
  lastSavedAt,
  mappingEnabled = true,
  onSwitchPath,
  onBranchFromHere,
  onOpenPaths,
  onComparePaths,
  onOpenMap,
  onEditCurrentCondition,
  focusMode = false,
  onExitFocus,
  dailyDate = null,
  onOpenJournalCalendar,
}: Props) {
  const t = useT();
  // Human-readable label for the open journal — uses the browser locale so
  // date formatting matches the rest of the app's "today" pill.
  const dailyLabel = useMemo(() => {
    if (!dailyDate) return null;
    const [y, m, d] = dailyDate.split("-").map(Number);
    if (!y || !m || !d) return dailyDate;
    return new Date(y, m - 1, d).toLocaleDateString(undefined, {
      weekday: "short", month: "short", day: "numeric",
    });
  }, [dailyDate]);
  const active = currentPath || rootName || "main";
  const byName = useMemo(() => {
    const m = new Map<string, PathCollection>();
    for (const c of collections) m.set(c.name, c);
    return m;
  }, [collections]);
  const activeCol = byName.get(active) ?? null;
  const condition = (activeCol?.condition || "").trim();
  const colorOverrides = useMemo(() => buildPathColorMap(collections), [collections]);
  const color = colorForPath(active, { overrides: colorOverrides });
  const root = active === rootName || isRoot(active);

  // "Saved just now" flash
  const [justSaved, setJustSaved] = useState(false);
  useEffect(() => {
    if (!lastSavedAt) return;
    setJustSaved(true);
    const t = window.setTimeout(() => setJustSaved(false), 2500);
    return () => window.clearTimeout(t);
  }, [lastSavedAt]);

  const saveLabel = dirty
    ? t("editor.toolbar.editing")
    : justSaved
      ? t("editor.toolbar.savedJustNow")
      : t("editor.toolbar.saved");
  const saveDotColor = dirty ? "var(--yel)" : justSaved ? "var(--yel)" : "var(--accent2)";

  // Switcher dropdown
  const [open, setOpen] = useState(false);
  const switcherRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    const onDown = (e: MouseEvent) => {
      if (!switcherRef.current?.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("mousedown", onDown);
    window.addEventListener("keydown", onKey);
    return () => {
      window.removeEventListener("mousedown", onDown);
      window.removeEventListener("keydown", onKey);
    };
  }, [open]);

  // Shared pill used in both toolbar variants below. Only renders when the
  // active note is a daily journal; clicking it opens the month calendar
  // as a popover anchored right below the pill.
  const journalPill = dailyDate && onOpenJournalCalendar ? (
    <button
      onClick={(e) => {
        const rect = (e.currentTarget as HTMLButtonElement).getBoundingClientRect();
        onOpenJournalCalendar(rect);
      }}
      className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-yeld bg-yelp/60 hover:bg-yelp transition border border-yel/25"
      title={t("editor.toolbar.journalJump")}
    >
      <JournalIcon size={13} />
      <span className="font-serif">{dailyLabel}</span>
      <span className="text-t3 text-[11px]">▾</span>
    </button>
  ) : null;

  if (!mappingEnabled) {
    return (
      <div className="toolbar h-11 flex items-center px-6 gap-2 text-xs border-b border-bd bg-bg">
        {journalPill}
        <div className="flex-1" />
        {focusMode && <ZenChip onExit={onExitFocus} />}
        <div className="flex items-center gap-3 text-2xs text-t3 shrink-0 whitespace-nowrap">
          <span className="font-mono">{t("editor.toolbar.checkpoints", { count: String(checkpointCount) })}</span>
          <span className="flex items-center gap-1.5 transition-[color] duration-500">
            <StatusDot color={saveDotColor} size={5} />
            <span className={justSaved && !dirty ? "text-yeld" : ""}>{saveLabel}</span>
          </span>
        </div>
      </div>
    );
  }

  return (
    <div className="toolbar h-11 flex items-center px-6 gap-2 text-xs border-b border-bd bg-bg">
      {/* ── Path pill (colored dot + name + condition) ── */}
      <div className="relative" ref={switcherRef}>
        <button
          onClick={() => setOpen((o) => !o)}
          className="flex items-center gap-2 pl-1.5 pr-3 py-1 rounded-full hover:bg-s2 transition group max-w-[480px]"
          title={t("editor.toolbar.switchPath")}
        >
          <span
            className="inline-block w-2.5 h-2.5 rounded-full shrink-0 ring-2 ring-bg"
            style={{ background: color }}
          />
          <span className="font-serif text-[15px] text-char leading-none whitespace-nowrap">
            {active}
          </span>
          {!root && (
            condition ? (
              <span
                className="font-serif italic text-[13px] text-yeld truncate max-w-[300px] leading-none"
                title={condition}
              >
                “{condition}”
              </span>
            ) : (
              <span
                className="font-serif italic text-[12px] text-t3 truncate leading-none"
                onClick={(e) => {
                  e.stopPropagation();
                  onEditCurrentCondition();
                }}
                role="button"
                title={t("editor.toolbar.namePathTitle")}
              >
                {t("editor.toolbar.namePathPrompt")}
              </span>
            )
          )}
          {root && collections.length <= 1 && (
            <span className="text-2xs italic text-t3 leading-none">
              {t("editor.toolbar.onlyPath")}
            </span>
          )}
          <svg
            className="text-t3 group-hover:text-char shrink-0"
            width="10" height="10" viewBox="0 0 10 10" fill="none"
          >
            <path d="M2 4l3 3 3-3" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </button>

        {open && (
          <PathSwitcher
            collections={collections}
            rootName={rootName}
            current={active}
            onPick={(name) => { setOpen(false); onSwitchPath(name); }}
            onOpenPaths={() => { setOpen(false); onOpenPaths(); }}
          />
        )}
      </div>

      {/* ── "Back to main" quick pill (only when off-main) ── */}
      {!root && rootName && (
        <button
          onClick={() => onSwitchPath(rootName)}
          className="flex items-center gap-1.5 pl-1.5 pr-2.5 py-1 rounded-full border border-yel/70 text-yeld hover:bg-yelp transition group"
          title={t("editor.toolbar.backToRoot", { root: rootName })}
        >
          <span
            className="inline-block w-2 h-2 rounded-full shrink-0"
            style={{ background: "var(--yel)" }}
          />
          <span className="font-serif text-[12.5px] leading-none whitespace-nowrap">
            {t("editor.toolbar.backArrow", { root: rootName })}
          </span>
        </button>
      )}

      {/* ── Actions ── */}
      <div className="ml-1 flex items-center gap-1.5 shrink-0">
        <button
          onClick={onBranchFromHere}
          className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
          title={t("editor.toolbar.branchThisTitle", { shortcut: "⌘⇧B" })}
        >
          <NewDirectionIcon />
          <span>{t("editor.toolbar.branchThis")}</span>
        </button>
        <button
          onClick={onOpenMap}
          className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
          title={t("editor.toolbar.connectionsMapTitle")}
        >
          <ConnectionsMapIcon />
          <span>{t("editor.toolbar.connectionsMap")}</span>
        </button>
        <button
          onClick={onOpenPaths}
          className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
          title={t("editor.toolbar.pathsTitle")}
        >
          <GraphIcon />
          <span>{t("editor.toolbar.paths")}</span>
        </button>
        {onComparePaths && collections.length > 1 && (
          <button
            onClick={onComparePaths}
            className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
            title={t("editor.toolbar.compareTitle")}
          >
            <CompareIcon />
            <span>{t("editor.toolbar.compare")}</span>
          </button>
        )}
        {journalPill}
      </div>

      <div className="flex-1" />

      {focusMode && <ZenChip onExit={onExitFocus} />}

      {/* ── Save status ── */}
      <div className="flex items-center gap-3 text-2xs text-t3 shrink-0 whitespace-nowrap">
        <span className="font-mono">{t("editor.toolbar.checkpoints", { count: String(checkpointCount) })}</span>
        <span className="flex items-center gap-1.5 transition-[color] duration-500">
          <StatusDot color={saveDotColor} size={5} />
          <span className={justSaved && !dirty ? "text-yeld" : ""}>{saveLabel}</span>
        </span>
      </div>
    </div>
  );
}

/** Persistent "you're in zen mode" indicator with an explicit exit.
 *  Shown in the Toolbar whenever focus/zen mode is active so the user
 *  always has a way out — the keyboard shortcut alone isn't enough if
 *  they don't remember they turned it on. */
function ZenChip({ onExit }: { onExit?: () => void }) {
  const t = useT();
  return (
    <div
      className="flex items-center gap-2.5 pl-3 pr-1.5 py-1.5 rounded-full bg-yelp border border-yeld/30 shrink-0"
      title={t("editor.toolbar.zenTitle")}
      // Cranked up on-screen legibility for the small italic serif —
      // webkit2gtk renders sub-14px italics poorly otherwise.
      style={{
        WebkitFontSmoothing: "antialiased",
        MozOsxFontSmoothing: "grayscale",
        textRendering: "optimizeLegibility",
      }}
    >
      <span className="relative flex items-center justify-center">
        <span className="absolute inline-block w-2 h-2 rounded-full bg-yel opacity-60 animate-ping" />
        <span className="relative inline-block w-1.5 h-1.5 rounded-full bg-yel" />
      </span>
      <span className="font-serif italic text-[14px] text-yeld leading-[1.1] tracking-[0.01em]">
        {t("editor.toolbar.zenLabel")}
      </span>
      <button
        onClick={onExit}
        className="font-mono text-[11px] text-yeld hover:text-char hover:bg-bg px-2 py-1 rounded-full border border-yeld/35 hover:border-yeld transition leading-none"
        title={t("editor.toolbar.zenExitTitle", { shortcut: SK.focusToggle })}
      >
        {t("editor.toolbar.zenExit")}
      </button>
    </div>
  );
}

function PathSwitcher({
  collections,
  rootName,
  current,
  onPick,
  onOpenPaths,
}: {
  collections: PathCollection[];
  rootName: string;
  current: string;
  onPick: (name: string) => void;
  onOpenPaths: () => void;
}) {
  const t = useT();
  const [filter, setFilter] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    const t = window.setTimeout(() => inputRef.current?.focus(), 20);
    return () => window.clearTimeout(t);
  }, []);

  // Sort live paths: current first, root second (unless it's the current),
  // then by created_at desc. Ghosts get their own section below — they're
  // still switchable (PathDetail exposes promote-back from there), but
  // visually separated so the live tree reads first.
  const { liveOrdered, ghostOrdered } = useMemo(() => {
    const q = filter.trim().toLowerCase();
    const match = (c: PathCollection) =>
      !q ||
      c.name.toLowerCase().includes(q) ||
      c.condition.toLowerCase().includes(q);
    const live = collections.filter((c) => !isGhostPath(c, rootName, collections) && match(c));
    const ghost = collections.filter((c) => isGhostPath(c, rootName, collections) && match(c));
    live.sort((a, b) => {
      if (a.name === current) return -1;
      if (b.name === current) return 1;
      const aRoot = a.name === rootName ? 1 : 0;
      const bRoot = b.name === rootName ? 1 : 0;
      if (aRoot !== bRoot) return bRoot - aRoot;
      return (b.created_at || 0) - (a.created_at || 0);
    });
    ghost.sort((a, b) => {
      // Group by permanent trunk (era); trunk anchor first, peers by
      // creation desc. A ghost's "era key" is its parent, or its own name
      // if it was itself an original root.
      const aEra = a.parent || a.name;
      const bEra = b.parent || b.name;
      if (aEra !== bEra) return bEra.localeCompare(aEra);
      const aAnchor = a.name === aEra ? -1 : 0;
      const bAnchor = b.name === bEra ? -1 : 0;
      if (aAnchor !== bAnchor) return aAnchor - bAnchor;
      return (b.created_at || 0) - (a.created_at || 0);
    });
    return { liveOrdered: live, ghostOrdered: ghost };
  }, [collections, rootName, current, filter]);

  const colorOverrides = useMemo(() => buildPathColorMap(collections), [collections]);
  const onCurrentRoot = current === rootName;

  return (
    <div
      className="absolute left-0 top-full mt-1 z-50 w-[380px] bg-bg border border-bd2 rounded-lg shadow-2xl py-1.5 animate-fadeIn"
    >
      <div className="px-3 pt-1.5 pb-2">
        <input
          ref={inputRef}
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          placeholder={t("editor.pathSwitcher.placeholder", { count: String(collections.length) })}
          className="w-full px-2.5 py-1.5 bg-s1 border border-bd rounded-md text-char text-xs placeholder:text-t3 focus:outline-none focus:border-yel"
        />
      </div>
      {!onCurrentRoot && (
        <button
          onClick={() => onPick(rootName)}
          className="w-full text-left px-3.5 py-1.5 text-xs text-yeld hover:bg-yelp flex items-center gap-2 border-b border-bd"
          title={t("editor.pathSwitcher.backToRootTitle")}
        >
          <span className="inline-block w-2 h-2 rounded-full bg-yel" />
          <span className="font-medium">{t("editor.pathSwitcher.backToRoot", { root: rootName })}</span>
        </button>
      )}
      <ul className="max-h-[360px] overflow-y-auto">
        {liveOrdered.length === 0 && ghostOrdered.length === 0 && (
          <li className="px-3.5 py-3 text-xs text-t3 italic">
            {t("editor.pathSwitcher.noMatches")}
          </li>
        )}
        {liveOrdered.map((c) => {
          const cond = c.condition.trim();
          const color =
            colorOverrides[c.name] ??
            (c.name === rootName ? "var(--yel)" : colorForPath(c.name));
          const isActive = c.name === current;
          const isRootItem = c.name === rootName;
          return (
            <li key={c.name}>
              <button
                onClick={() => onPick(c.name)}
                className={`w-full text-left px-3.5 py-2 flex items-start gap-2.5 transition ${
                  isActive ? "bg-yelp/60" : "hover:bg-s2/70"
                }`}
              >
                <span
                  className="inline-block w-2.5 h-2.5 rounded-full mt-1 shrink-0"
                  style={{ background: color }}
                />
                <div className="flex-1 min-w-0">
                  <div className="flex items-baseline gap-2">
                    <span className="font-serif text-[14.5px] text-char truncate">
                      {c.name}
                    </span>
                    {isActive && (
                      <span className="text-2xs font-mono text-yeld tracking-wider">
                        {t("editor.pathSwitcher.you")}
                      </span>
                    )}
                    {isRootItem && !isActive && (
                      <span className="text-2xs font-mono text-t3 tracking-wider">
                        {t("editor.pathSwitcher.main")}
                      </span>
                    )}
                  </div>
                  {cond ? (
                    <div className="text-2xs text-yeld italic truncate mt-0.5">
                      “{cond}”
                    </div>
                  ) : !isRootItem ? (
                    <div className="text-2xs text-t3 italic truncate mt-0.5">
                      {t("editor.pathSwitcher.unnamedPath")}
                    </div>
                  ) : null}
                  <div className="text-2xs text-t3 mt-1 font-mono">
                    {c.members.length === 1
                      ? t("editor.pathSwitcher.notesCountOne", { count: String(c.members.length) })
                      : t("editor.pathSwitcher.notesCountOther", { count: String(c.members.length) })}
                  </div>
                </div>
              </button>
            </li>
          );
        })}
        {ghostOrdered.length > 0 && (
          <li className="px-3.5 pt-3 pb-1 text-2xs font-mono uppercase tracking-[0.18em] text-t3 border-t border-bd mt-1">
            {t("editor.pathSwitcher.ghostsHeader")}
          </li>
        )}
        {ghostOrdered.map((c) => {
          const cond = c.condition.trim();
          const isActive = c.name === current;
          // A ghost anchors its own era when its own name matches its era
          // key — i.e., it was an original trunk before being ghosted.
          const era = c.parent || c.name;
          const isAnchor = c.name === era;
          return (
            <li key={c.name}>
              <button
                onClick={() => onPick(c.name)}
                className={`w-full text-left px-3.5 py-2 flex items-start gap-2.5 transition opacity-75 hover:opacity-100 ${
                  isActive ? "bg-yelp/60" : "hover:bg-s2/70"
                }`}
              >
                <span
                  className="inline-block w-2.5 h-2.5 rounded-full mt-1 shrink-0 border border-dashed border-t3"
                  style={{ background: "transparent" }}
                />
                <div className="flex-1 min-w-0">
                  <div className="flex items-baseline gap-2">
                    <span className="font-serif italic text-[14.5px] text-t2 truncate">
                      {c.name}
                    </span>
                    {isAnchor && (
                      <span className="text-2xs font-mono text-t3 tracking-wider">
                        {t("editor.pathSwitcher.wasMain")}
                      </span>
                    )}
                  </div>
                  {cond && (
                    <div className="text-2xs text-t3 italic truncate mt-0.5">
                      “{cond}”
                    </div>
                  )}
                  <div className="text-2xs text-t3 mt-1 font-mono">
                    {c.members.length === 1
                      ? t("editor.pathSwitcher.ghostNotesOne", { count: String(c.members.length) })
                      : t("editor.pathSwitcher.ghostNotesOther", { count: String(c.members.length) })}
                  </div>
                </div>
              </button>
            </li>
          );
        })}
      </ul>
      <div className="border-t border-bd mt-1 pt-1">
        <button
          onClick={onOpenPaths}
          className="w-full text-left px-3.5 py-2 text-xs text-t2 hover:bg-s2 hover:text-char flex items-center gap-2 transition"
        >
          <GraphIcon />
          <span>{t("editor.toolbar.openPathsGraph")}</span>
        </button>
      </div>
    </div>
  );
}

function GraphIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round">
      <circle cx="3" cy="3" r="1.5" />
      <circle cx="3" cy="11" r="1.5" />
      <circle cx="11" cy="7" r="1.5" />
      <path d="M3 4.5v5M4.3 3.7l5.4 2.6M4.3 10.3l5.4-2.6" />
    </svg>
  );
}

/** Triangle of connected dots — matches the right tool-rail's Map icon so
 *  the two entry-points share a visual language. */
function ConnectionsMapIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="3" cy="3" r="1.6" />
      <circle cx="11" cy="3" r="1.6" />
      <circle cx="7" cy="11" r="1.6" />
      <path d="M4.2 4.1L5.8 9.7M8.2 9.7L9.8 4.1M4.6 3h4.8" />
    </svg>
  );
}

/** Two parallel columns with a divider — reads as "side by side" at a glance. */
function CompareIcon() {
  return (
    <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round">
      <rect x="1.5" y="2" width="4.5" height="10" rx="0.8" />
      <rect x="8" y="2" width="4.5" height="10" rx="0.8" />
      <path d="M7 2.5v9" strokeDasharray="1.2 1.3" />
    </svg>
  );
}

// memo so the path ribbon doesn't re-render every keystroke just because
// its parent re-rendered (e.g. on selection-change events). All the
// reference-stable props it actually depends on rarely change.
export default memo(ToolbarInner);

// src/components/Editor/Toolbar.svelte
<script lang="ts">
  import { NewDirectionIcon, JournalIcon } from "../../lib/iconsSvelte";
  import type { PathCollection } from "../../lib/types";
  import { isGhostPath } from "../../lib/types";
  import { buildPathColorMap, colorForPath, isRoot } from "../../lib/pathAwareness";
  import { tr } from "../../lib/i18n/index.svelte";
  import { SK } from "../../lib/platform.svelte";

  interface Props {
    collections: PathCollection[];
    rootName: string;
    currentPath: string;
    checkpointCount: number;
    dirty: boolean;
    lastSavedAt?: number;
    mappingEnabled?: boolean;
    onSwitchPath: (name: string) => void;
    onBranchFromHere: () => void;
    onOpenPaths: () => void;
    onComparePaths?: () => void;
    onOpenMap: () => void;
    onEditCurrentCondition: () => void;
    focusMode?: boolean;
    onExitFocus?: () => void;
    dailyDate?: string | null;
    onOpenJournalCalendar?: (anchor: DOMRect) => void;
    onBack?: () => void;
    backLabel?: string | null;
    backShortcut?: string;
  }

  let {
    collections,
    rootName,
    currentPath,
    checkpointCount,
    dirty,
    lastSavedAt,
    mappingEnabled = true,
    onSwitchPath,
    onBranchFromHere,
    onOpenPaths,
    onComparePaths,
    onOpenMap,
    onEditCurrentCondition,
    focusMode = false,
    onExitFocus,
    dailyDate = null,
    onOpenJournalCalendar,
    onBack,
    backLabel = null,
    backShortcut,
  }: Props = $props();

  let t = $derived(tr());

  let dailyLabel = $derived.by(() => {
    if (!dailyDate) return null;
    const [y, m, d] = dailyDate.split("-").map(Number);
    if (!y || !m || !d) return dailyDate;
    return new Date(y, m - 1, d).toLocaleDateString(undefined, {
      weekday: "short", month: "short", day: "numeric",
    });
  });

  let active = $derived(currentPath || rootName || "main");
  let byName = $derived.by(() => {
    const m = new Map<string, PathCollection>();
    for (const c of collections) m.set(c.name, c);
    return m;
  });
  let activeCol = $derived(byName.get(active) ?? null);
  let condition = $derived((activeCol?.condition || "").trim());
  let colorOverrides = $derived(buildPathColorMap(collections));
  let color = $derived(colorForPath(active, { overrides: colorOverrides }));
  let root = $derived(active === rootName || isRoot(active));

  let justSaved = $state(false);
  $effect(() => {
    if (!lastSavedAt) return;
    justSaved = true;
    const handle = window.setTimeout(() => (justSaved = false), 2500);
    return () => window.clearTimeout(handle);
  });

  let saveLabel = $derived(
    dirty
      ? t("editor.toolbar.editing")
      : justSaved
      ? t("editor.toolbar.savedJustNow")
      : t("editor.toolbar.saved"),
  );
  let saveDotColor = $derived(dirty ? "var(--yel)" : justSaved ? "var(--yel)" : "var(--accent2)");

  let switcherOpen = $state(false);
  let switcherRef = $state<HTMLDivElement | null>(null);
  $effect(() => {
    if (!switcherOpen) return;
    const onDown = (e: MouseEvent) => {
      if (!switcherRef?.contains(e.target as Node)) switcherOpen = false;
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") switcherOpen = false;
    };
    window.addEventListener("mousedown", onDown);
    window.addEventListener("keydown", onKey);
    return () => {
      window.removeEventListener("mousedown", onDown);
      window.removeEventListener("keydown", onKey);
    };
  });

  // PathSwitcher state
  let filter = $state("");
  let filterInputRef = $state<HTMLInputElement | null>(null);
  $effect(() => {
    if (!switcherOpen) return;
    filter = "";
    const h = window.setTimeout(() => filterInputRef?.focus(), 20);
    return () => window.clearTimeout(h);
  });

  let liveOrdered = $derived.by(() => {
    const q = filter.trim().toLowerCase();
    const match = (c: PathCollection) =>
      !q ||
      c.name.toLowerCase().includes(q) ||
      c.condition.toLowerCase().includes(q);
    const live = collections.filter((c) => !isGhostPath(c, rootName, collections) && match(c));
    live.sort((a, b) => {
      if (a.name === active) return -1;
      if (b.name === active) return 1;
      const aRoot = a.name === rootName ? 1 : 0;
      const bRoot = b.name === rootName ? 1 : 0;
      if (aRoot !== bRoot) return bRoot - aRoot;
      return (b.created_at || 0) - (a.created_at || 0);
    });
    return live;
  });
  let ghostOrdered = $derived.by(() => {
    const q = filter.trim().toLowerCase();
    const match = (c: PathCollection) =>
      !q ||
      c.name.toLowerCase().includes(q) ||
      c.condition.toLowerCase().includes(q);
    const ghost = collections.filter((c) => isGhostPath(c, rootName, collections) && match(c));
    ghost.sort((a, b) => {
      const aEra = a.parent || a.name;
      const bEra = b.parent || b.name;
      if (aEra !== bEra) return bEra.localeCompare(aEra);
      const aAnchor = a.name === aEra ? -1 : 0;
      const bAnchor = b.name === bEra ? -1 : 0;
      if (aAnchor !== bAnchor) return aAnchor - bAnchor;
      return (b.created_at || 0) - (a.created_at || 0);
    });
    return ghost;
  });

  let onCurrentRoot = $derived(active === rootName);

  function pickPath(name: string) {
    switcherOpen = false;
    onSwitchPath(name);
  }
</script>

{#snippet backButton()}
  {#if onBack}
    <button
      type="button"
      onclick={onBack}
      class="flex items-center gap-1 pl-1.5 pr-2 py-1 rounded-md text-[12px] text-t2 hover:bg-s2 hover:text-char transition shrink-0"
      title={
        backLabel
          ? t("editor.toolbar.backTitle", { title: backLabel, shortcut: backShortcut ?? "" })
          : t("editor.toolbar.backTitleEmpty", { shortcut: backShortcut ?? "" })
      }
      aria-label={t("editor.toolbar.backAria")}
    >
      <span aria-hidden="true" style:font-size="13px">‹</span>
      <span>{t("editor.toolbar.back")}</span>
    </button>
  {/if}
{/snippet}

{#snippet journalPill()}
  {#if dailyDate && onOpenJournalCalendar}
    <button
      type="button"
      onclick={(e) => {
        const rect = (e.currentTarget as HTMLButtonElement).getBoundingClientRect();
        onOpenJournalCalendar(rect);
      }}
      class="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-yeld bg-yelp/60 hover:bg-yelp transition border border-yel/25"
      title={t("editor.toolbar.journalJump")}
    >
      <JournalIcon size={13} />
      <span class="font-serif">{dailyLabel}</span>
      <span class="text-t3 text-[11px]">▾</span>
    </button>
  {/if}
{/snippet}

{#snippet zenChip()}
  {#if focusMode}
    <div
      class="flex items-center gap-2.5 pl-3 pr-1.5 py-1.5 rounded-full bg-yelp border border-yeld/30 shrink-0"
      title={t("editor.toolbar.zenTitle")}
      style:-webkit-font-smoothing="antialiased"
      style:-moz-osx-font-smoothing="grayscale"
      style:text-rendering="optimizeLegibility"
    >
      <span class="relative flex items-center justify-center">
        <span class="absolute inline-block w-2 h-2 rounded-full bg-yel opacity-60 animate-ping"></span>
        <span class="relative inline-block w-1.5 h-1.5 rounded-full bg-yel"></span>
      </span>
      <span class="font-serif italic text-[14px] text-yeld leading-[1.1] tracking-[0.01em]">
        {t("editor.toolbar.zenLabel")}
      </span>
      <button
        type="button"
        onclick={onExitFocus}
        class="font-mono text-[11px] text-yeld hover:text-char hover:bg-bg px-2 py-1 rounded-full border border-yeld/35 hover:border-yeld transition leading-none"
        title={t("editor.toolbar.zenExitTitle", { shortcut: SK.focusToggle })}
      >
        {t("editor.toolbar.zenExit")}
      </button>
    </div>
  {/if}
{/snippet}

{#snippet saveStatus()}
  <div class="flex items-center gap-3 text-2xs text-t3 shrink-0 whitespace-nowrap">
    <span class="font-mono">{t("editor.toolbar.checkpoints", { count: String(checkpointCount) })}</span>
    <span class="flex items-center gap-1.5 transition-[color] duration-500">
      <span aria-hidden="true" class="inline-block rounded-full" style:width="5px" style:height="5px" style:background={saveDotColor}></span>
      <span class={justSaved && !dirty ? "text-yeld" : ""}>{saveLabel}</span>
    </span>
  </div>
{/snippet}

{#snippet graphIcon()}
  <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round">
    <circle cx="3" cy="3" r="1.5" />
    <circle cx="3" cy="11" r="1.5" />
    <circle cx="11" cy="7" r="1.5" />
    <path d="M3 4.5v5M4.3 3.7l5.4 2.6M4.3 10.3l5.4-2.6" />
  </svg>
{/snippet}

{#snippet connectionsMapIcon()}
  <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="3" cy="3" r="1.6" />
    <circle cx="11" cy="3" r="1.6" />
    <circle cx="7" cy="11" r="1.6" />
    <path d="M4.2 4.1L5.8 9.7M8.2 9.7L9.8 4.1M4.6 3h4.8" />
  </svg>
{/snippet}

{#snippet compareIcon()}
  <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round">
    <rect x="1.5" y="2" width="4.5" height="10" rx="0.8" />
    <rect x="8" y="2" width="4.5" height="10" rx="0.8" />
    <path d="M7 2.5v9" stroke-dasharray="1.2 1.3" />
  </svg>
{/snippet}

{#if !mappingEnabled}
  <div class="toolbar h-11 flex items-center px-6 gap-2 text-xs border-b border-bd bg-bg">
    {@render backButton()}
    {@render journalPill()}
    <div class="flex-1"></div>
    {@render zenChip()}
    {@render saveStatus()}
  </div>
{:else}
  <div class="toolbar h-11 flex items-center px-6 gap-2 text-xs border-b border-bd bg-bg">
    {@render backButton()}
    <div class="relative" bind:this={switcherRef}>
      <button
        type="button"
        onclick={() => (switcherOpen = !switcherOpen)}
        class="flex items-center gap-2 pl-1.5 pr-3 py-1 rounded-full hover:bg-s2 transition group max-w-[480px]"
        title={t("editor.toolbar.switchPath")}
      >
        <span class="inline-block w-2.5 h-2.5 rounded-full shrink-0 ring-2 ring-bg" style:background={color}></span>
        <span class="font-serif text-[15px] text-char leading-none whitespace-nowrap">{active}</span>
        {#if !root}
          {#if condition}
            <span class="font-serif italic text-[13px] text-yeld truncate max-w-[300px] leading-none" title={condition}>"{condition}"</span>
          {:else}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <span
              class="font-serif italic text-[12px] text-t3 truncate leading-none"
              onclick={(e) => { e.stopPropagation(); onEditCurrentCondition(); }}
              role="button"
              tabindex="0"
              title={t("editor.toolbar.namePathTitle")}
            >
              {t("editor.toolbar.namePathPrompt")}
            </span>
          {/if}
        {/if}
        {#if root && collections.length <= 1}
          <span class="text-2xs italic text-t3 leading-none">{t("editor.toolbar.onlyPath")}</span>
        {/if}
        <svg class="text-t3 group-hover:text-char shrink-0" width="10" height="10" viewBox="0 0 10 10" fill="none">
          <path d="M2 4l3 3 3-3" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      </button>

      {#if switcherOpen}
        <div class="absolute left-0 top-full mt-1 z-50 w-[380px] bg-bg border border-bd2 rounded-lg shadow-2xl py-1.5 animate-fadeIn">
          <div class="px-3 pt-1.5 pb-2">
            <input
              bind:this={filterInputRef}
              type="text"
              bind:value={filter}
              placeholder={t("editor.pathSwitcher.placeholder", { count: String(collections.length) })}
              class="w-full px-2.5 py-1.5 bg-s1 border border-bd rounded-md text-char text-xs placeholder:text-t3 focus:outline-hidden focus:border-yel"
            />
          </div>
          {#if !onCurrentRoot}
            <button
              type="button"
              onclick={() => pickPath(rootName)}
              class="w-full text-left px-3.5 py-1.5 text-xs text-yeld hover:bg-yelp flex items-center gap-2 border-b border-bd"
              title={t("editor.pathSwitcher.backToRootTitle")}
            >
              <span class="inline-block w-2 h-2 rounded-full bg-yel"></span>
              <span class="font-medium">{t("editor.pathSwitcher.backToRoot", { root: rootName })}</span>
            </button>
          {/if}
          <ul class="max-h-[360px] overflow-y-auto">
            {#if liveOrdered.length === 0 && ghostOrdered.length === 0}
              <li class="px-3.5 py-3 text-xs text-t3 italic">{t("editor.pathSwitcher.noMatches")}</li>
            {/if}
            {#each liveOrdered as c (c.name)}
              {@const cond = c.condition.trim()}
              {@const itemColor = colorOverrides[c.name] ?? (c.name === rootName ? "var(--yel)" : colorForPath(c.name))}
              {@const isActive = c.name === active}
              {@const isRootItem = c.name === rootName}
              <li>
                <button
                  type="button"
                  onclick={() => pickPath(c.name)}
                  class="w-full text-left px-3.5 py-2 flex items-start gap-2.5 transition {isActive ? 'bg-yelp/60' : 'hover:bg-s2/70'}"
                >
                  <span class="inline-block w-2.5 h-2.5 rounded-full mt-1 shrink-0" style:background={itemColor}></span>
                  <div class="flex-1 min-w-0">
                    <div class="flex items-baseline gap-2">
                      <span class="font-serif text-[14.5px] text-char truncate">{c.name}</span>
                      {#if isActive}
                        <span class="text-2xs font-mono text-yeld tracking-wider">{t("editor.pathSwitcher.you")}</span>
                      {/if}
                      {#if isRootItem && !isActive}
                        <span class="text-2xs font-mono text-t3 tracking-wider">{t("editor.pathSwitcher.main")}</span>
                      {/if}
                    </div>
                    {#if cond}
                      <div class="text-2xs text-yeld italic truncate mt-0.5">"{cond}"</div>
                    {:else if !isRootItem}
                      <div class="text-2xs text-t3 italic truncate mt-0.5">{t("editor.pathSwitcher.unnamedPath")}</div>
                    {/if}
                    <div class="text-2xs text-t3 mt-1 font-mono">
                      {c.members.length === 1
                        ? t("editor.pathSwitcher.notesCountOne", { count: String(c.members.length) })
                        : t("editor.pathSwitcher.notesCountOther", { count: String(c.members.length) })}
                    </div>
                  </div>
                </button>
              </li>
            {/each}
            {#if ghostOrdered.length > 0}
              <li class="px-3.5 pt-3 pb-1 text-2xs font-mono uppercase tracking-[0.18em] text-t3 border-t border-bd mt-1">
                {t("editor.pathSwitcher.ghostsHeader")}
              </li>
            {/if}
            {#each ghostOrdered as c (c.name)}
              {@const cond = c.condition.trim()}
              {@const isActive = c.name === active}
              {@const era = c.parent || c.name}
              {@const isAnchor = c.name === era}
              <li>
                <button
                  type="button"
                  onclick={() => pickPath(c.name)}
                  class="w-full text-left px-3.5 py-2 flex items-start gap-2.5 transition opacity-75 hover:opacity-100 {isActive ? 'bg-yelp/60' : 'hover:bg-s2/70'}"
                >
                  <span class="inline-block w-2.5 h-2.5 rounded-full mt-1 shrink-0 border border-dashed border-t3" style:background="transparent"></span>
                  <div class="flex-1 min-w-0">
                    <div class="flex items-baseline gap-2">
                      <span class="font-serif italic text-[14.5px] text-t2 truncate">{c.name}</span>
                      {#if isAnchor}
                        <span class="text-2xs font-mono text-t3 tracking-wider">{t("editor.pathSwitcher.wasMain")}</span>
                      {/if}
                    </div>
                    {#if cond}
                      <div class="text-2xs text-t3 italic truncate mt-0.5">"{cond}"</div>
                    {/if}
                    <div class="text-2xs text-t3 mt-1 font-mono">
                      {c.members.length === 1
                        ? t("editor.pathSwitcher.ghostNotesOne", { count: String(c.members.length) })
                        : t("editor.pathSwitcher.ghostNotesOther", { count: String(c.members.length) })}
                    </div>
                  </div>
                </button>
              </li>
            {/each}
          </ul>
          <div class="border-t border-bd mt-1 pt-1">
            <button
              type="button"
              onclick={() => { switcherOpen = false; onOpenPaths(); }}
              class="w-full text-left px-3.5 py-2 text-xs text-t2 hover:bg-s2 hover:text-char flex items-center gap-2 transition"
            >
              {@render graphIcon()}
              <span>{t("editor.toolbar.openPathsGraph")}</span>
            </button>
          </div>
        </div>
      {/if}
    </div>

    {#if !root && rootName}
      <button
        type="button"
        onclick={() => onSwitchPath(rootName)}
        class="flex items-center gap-1.5 pl-1.5 pr-2.5 py-1 rounded-full border border-yel/70 text-yeld hover:bg-yelp transition group"
        title={t("editor.toolbar.backToRoot", { root: rootName })}
      >
        <span class="inline-block w-2 h-2 rounded-full shrink-0" style:background="var(--yel)"></span>
        <span class="font-serif text-[12.5px] leading-none whitespace-nowrap">{t("editor.toolbar.backArrow", { root: rootName })}</span>
      </button>
    {/if}

    <div class="ml-1 flex items-center gap-1.5 shrink-0">
      <button
        type="button"
        onclick={onBranchFromHere}
        class="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
        title={t("editor.toolbar.branchThisTitle", { shortcut: "⌘⇧B" })}
      >
        <NewDirectionIcon />
        <span>{t("editor.toolbar.branchThis")}</span>
      </button>
      <button
        type="button"
        onclick={onOpenMap}
        class="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
        title={t("editor.toolbar.connectionsMapTitle")}
      >
        {@render connectionsMapIcon()}
        <span>{t("editor.toolbar.connectionsMap")}</span>
      </button>
      <button
        type="button"
        onclick={onOpenPaths}
        class="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
        title={t("editor.toolbar.pathsTitle")}
      >
        {@render graphIcon()}
        <span>{t("editor.toolbar.paths")}</span>
      </button>
      {#if onComparePaths && collections.length > 1}
        <button
          type="button"
          onclick={onComparePaths}
          class="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[12.5px] text-t2 hover:bg-s2 hover:text-char transition"
          title={t("editor.toolbar.compareTitle")}
        >
          {@render compareIcon()}
          <span>{t("editor.toolbar.compare")}</span>
        </button>
      {/if}
      {@render journalPill()}
    </div>

    <div class="flex-1"></div>
    {@render zenChip()}
    {@render saveStatus()}
  </div>
{/if}
