// src/App.tsx
import { useEffect, useState } from "react";
import { api } from "./lib/tauri";
import Onboarding from "./components/Onboarding";
import AppShell from "./components/AppShell";
import Titlebar from "./components/Titlebar";
import WindowResizeEdges from "./components/WindowResizeEdges";
import { useTheme } from "./lib/theme";
// Side-effect import: applies the saved UI font + scale at module-load
// time so even the Onboarding screen renders in the user's preferred
// chrome face, not a flash of Inter.
import "./lib/uiPrefs";

export default function App() {
  useTheme();
  const [workspacePath, setWorkspacePath] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.activeWorkspace().then((p) => {
      setWorkspacePath(p);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  return (
    <div className="h-full flex flex-col relative">
      <WindowResizeEdges />
      <Titlebar />
      <div className="flex-1 min-h-0">
        {loading ? (
          <div className="h-full flex items-center justify-center text-t2">loading…</div>
        ) : !workspacePath ? (
          <Onboarding onReady={setWorkspacePath} />
        ) : (
          // Key by path so switching workspaces fully remounts AppShell —
          // every piece of state (active note, paths, caches) is scoped to
          // the previous workspace and has no business surviving the jump.
          <AppShell
            key={workspacePath}
            workspacePath={workspacePath}
            onClose={() => setWorkspacePath(null)}
            onSwitchWorkspace={setWorkspacePath}
          />
        )}
      </div>
    </div>
  );
}

// src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { api } from "./lib/tauri";
  import IntroPage from "./components/IntroPage.svelte";
  import AppShell from "./components/AppShell.svelte";
  import Titlebar from "./components/Titlebar.svelte";
  import ExternalUrlFallbackModal from "./components/ExternalUrlFallbackModal.svelte";
  // Side-effect imports — these singleton stores self-apply via
  // `$effect.root` on first import, so just bringing them into the
  // module graph is enough to make the saved theme / a11y / mode /
  // ui-font / paper / language preferences land on <html> before the
  // first paint of any pane.
  import "./lib/theme.svelte";
  import "./lib/uiPrefs.svelte";
  import "./lib/paperPrefs.svelte";
  import "./lib/language.svelte";
  import "./lib/mode.svelte";
  import { installAccessibilityApplier } from "./lib/accessibilityPrefs.svelte";
  import { installExternalLinkInterceptor } from "./lib/openExternal";
  import { setWorkspaceScope } from "./lib/workspaceScope.svelte";

  let workspacePath = $state<string | null>(null);
  let loading = $state(true);

  // Centralised setter — every workspace transition (open / close /
  // switch / first-load) must funnel through here so the workspace
  // scope flips *before* the AppShell tree re-renders, ensuring every
  // store (theme, mode, paper, …) reads the correct scoped value on
  // its first read in the new workspace.
  function setWorkspacePath(p: string | null) {
    setWorkspaceScope(p);
    try {
      if (p) localStorage.setItem("yarrow.lastActiveWorkspace", p);
      else localStorage.removeItem("yarrow.lastActiveWorkspace");
    } catch {}
    workspacePath = p;
  }

  onMount(() => {
    installAccessibilityApplier();
    const removeInterceptor = installExternalLinkInterceptor();
    api
      .activeWorkspace()
      .then((p) => {
        setWorkspacePath(p);
        loading = false;
      })
      .catch(() => {
        loading = false;
      });
    return () => {
      removeInterceptor();
    };
  });
</script>

<div class="h-full flex flex-col relative">
  <Titlebar />
  <div class="flex-1 min-h-0 flex flex-col">
    {#if loading}
      <div class="flex-1 flex items-center justify-center text-t2">loading…</div>
    {:else if !workspacePath}
      <IntroPage onReady={setWorkspacePath} />
    {:else}
      {#key workspacePath}
        <AppShell
          {workspacePath}
          onClose={() => setWorkspacePath(null)}
          onSwitchWorkspace={setWorkspacePath}
        />
      {/key}
    {/if}
  </div>
  <ExternalUrlFallbackModal />
</div>
